language: ruby
cache: bundler
rvm:
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby
script: bundle exec rspec spec
gemfile:
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile